CREATE TABLE HOTEL (
    HOTEL_ID NVARCHAR(255) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    LOCATION NVARCHAR(255),
    RATING FLOAT,
    REVIEW_COUNT INT
);

-- 객실 테이블 생성
CREATE TABLE ROOM (
    HOTEL_ID VARCHAR(255),
    ROOM_ID INT PRIMARY KEY IDENTITY(1, 1),
    TYPE NVARCHAR(255) NOT NULL,
    PRICE INT,
    RESERVATION_LINK VARCHAR(255),
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

-- 리뷰 테이블 생성 
CREATE TABLE REVIEW (
    HOTEL_ID VARCHAR(255),
    REVIEW_ID INT PRIMARY KEY IDENTITY(1, 1),
    RATING FLOAT,
    COMMENT TEXT,
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);