-- 호텔 테이블 생성
-- CREATE TABLE HOTEL (
--     HOTEL_ID VARCHAR(255) PRIMARY KEY,
--     NAME VARCHAR(255) NOT NULL,
--     LOCATION VARCHAR(255),
--     RATING FLOAT,
--     OVERVIEW TEXT,
--     TOTAL_ROOMS INT,
--     CHECK_IN_INFO TEXT,
--     CHECK_OUT_INFO TEXT,
--     PARKING_INFO TEXT,
--     SMOKING_POLICY TEXT,
--     PET_POLICY TEXT,
--     MINOR_POLICY TEXT,
--     ADDITIONAL_FEES TEXT,
--     ROOM_DESIGN_POLICY TEXT,
--     PROMOTIONS TEXT
-- );
-- 수정
CREATE TABLE HOTEL (
    HOTEL_ID NVARCHAR(255) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    LOCATION NVARCHAR(255),
    RATING FLOAT,
    MAINREVIEW NVARCHAR(MAX),
    INFOMATION NVARCHAR(MAX)
);

-- 객실 테이블 생성
CREATE TABLE ROOM (
    ROOM_ID INT PRIMARY KEY IDENTITY(1, 1),
    HOTEL_ID VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL,
    STANDARD_CAPACITY INT,
    MAX_CAPACITY INT,
    RESERVATION_LINK VARCHAR(255),
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

-- 평가 테이블 생성
CREATE TABLE REVIEW (
    REVIEW_ID INT PRIMARY KEY IDENTITY(1, 1),
    HOTEL_ID VARCHAR(255),
    RATING FLOAT,
    COMMENT TEXT,
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);