CREATE TABLE HOTEL (
    HOTEL_ID NVARCHAR(255) PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    LOCATION NVARCHAR(255),
    RATING FLOAT
);

-- 객실 테이블 생성
CREATE TABLE ROOM (
    ROOM_ID INT PRIMARY KEY IDENTITY(1, 1),
    HOTEL_ID VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL,
 -- 사진추가
 -- 가격추가
 -- 후기수추가
    STANDARD_CAPACITY INT,
    #삭제 MAX_CAPACITY INT,
    #삭제 RESERVATION_LINK VARCHAR(255),
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);

-- 평가 테이블 생성 (100~500)
CREATE TABLE REVIEW (
    REVIEW_ID INT PRIMARY KEY IDENTITY(1, 1),
    HOTEL_ID VARCHAR(255),
    RATING FLOAT,
    COMMENT TEXT,
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
);