SELECT * FROM HOTEL;

-- Hotel table 수정 hotel_infomation 컬럼 추가
-- ALTER TABLE HOTEL DROP MAINREVIEW;

-- ALTER TABLE HOTEL
-- ALTER COLUMN HOTEL_ID NVARCHAR(255);

-- ALTER TABLE HOTEL
-- ALTER COLUMN NAME NVARCHAR(255);

-- ALTER TABLE HOTEL
-- ALTER COLUMN LOCATION NVARCHAR(255);

-- ALTER TABLE HOTEL
-- ALTER COLUMN MAINREVIEW NVARCHAR(MAX);


-- ALTER TABLE HOTEL
-- ALTER COLUMN INFOMATION NVARCHAR(MAX);
