SELECT
    *
FROM
    REVIEW;

-- SELECT * FROM HOTEL;
-- SELECT * FROM ROOM;



-- ALTER TABLE REVIEW DROP COLUMN COMMENT;

-- ALTER TABLE REVIEW ADD COMMENT NVARCHAR(MAX);

-- ALTER TABLE ROOM ADD IMAGE_LINK VARCHAR(255);

-- REIVEW TABLE 삭제
-- DROP TABLE REVIEW;

-- 리뷰 테이블 생성
-- CREATE TABLE REVIEW (
--     REVIEW_ID INT PRIMARY KEY IDENTITY(1, 1),
--     HOTEL_ID VARCHAR(255),
--     REVIEW_COUNT INT,
--     RATING FLOAT,
--     COMMENT TEXT,
--     FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
-- );

-- -- 객실 테이블 생성
-- CREATE TABLE ROOM (
--     HOTEL_ID VARCHAR(255),
--     ROOM_ID INT PRIMARY KEY IDENTITY(1, 1),
--     TYPE NVARCHAR(255) NOT NULL,
--     PRICE INT,
--     RESERVATION_LINK VARCHAR(255),
--     FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
-- );

-- ROOM 테이블 값 전부 삭제
-- DELETE FROM REVIEW;

-- 리뷰 테이블 생성
-- CREATE TABLE REVIEW (
--     HOTEL_ID VARCHAR(255),
--     REVIEW_ID INT PRIMARY KEY IDENTITY(1, 1),
--     RATING FLOAT,
--     COMMENT NVARCHAR(MAX),
--     FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID)
-- );